// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POne_to_One.Entities;

#nullable disable

namespace POne_to_One.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250108044045_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POne_to_One.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "Science",
                            StudentId = 2
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Social",
                            StudentId = 1
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "Maths",
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("POne_to_One.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Surya",
                            LastName = "Tejas"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Arya",
                            LastName = "Teja"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Suresh",
                            LastName = "Kumar"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Aditi",
                            LastName = "Prabhu"
                        });
                });

            modelBuilder.Entity("POne_to_One.Entities.Course", b =>
                {
                    b.HasOne("POne_to_One.Entities.Student", "Student")
                        .WithOne("Course")
                        .HasForeignKey("POne_to_One.Entities.Course", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("POne_to_One.Entities.Student", b =>
                {
                    b.Navigation("Course")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
