using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DTOModels.Dtos
{
    public  class UserResponseDTO
    {
        public int UserId { get; set; }  // The unique identifier for the user, usually generated by the database.
        public string UserName { get; set; }  // The user's name, which was provided in the request.
        public UserProfileDto UserProfile { get; set; }
    }
}
